# Generated by Django 4.1.3 on 2022-11-25 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0002_club_andinist_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mountainprefix',
            options={'verbose_name': 'Prefijo de montaña', 'verbose_name_plural': 'Prefijos de montaña'},
        ),
    ]
