# Generated by Django 4.1.3 on 2022-11-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0003_alter_mountainprefix_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountain',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='region',
        ),
        migrations.AddField(
            model_name='mountain',
            name='countries',
            field=models.ManyToManyField(blank=True, to='cerros.country'),
        ),
        migrations.AddField(
            model_name='mountain',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cerros.region'),
        ),
    ]
