# Generated by Django 4.1.3 on 2022-12-01 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0004_remove_mountain_country_remove_mountain_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication_name', models.CharField(max_length=255)),
                ('publication_edition', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
        migrations.AlterModelOptions(
            name='andinist',
            options={'verbose_name': 'Andinista', 'verbose_name_plural': 'Andinistas'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Club', 'verbose_name_plural': 'Clubes'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='mountain',
            options={'verbose_name': 'Referenciable', 'verbose_name_plural': 'Referenciables'},
        ),
        migrations.AlterModelOptions(
            name='mountaingroup',
            options={'verbose_name': 'Grupo de Montañas', 'verbose_name_plural': 'Grupos de Montañas'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.RemoveField(
            model_name='andinist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='andinist',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='club',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='club',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mountaingroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mountaingroup',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summit', models.BooleanField(default=True)),
                ('ascended', models.BooleanField(default=False)),
                ('alpine_grade', models.IntegerField(choices=[(0, 'F'), (1, 'PD-'), (2, 'PD'), (3, 'PD+'), (4, 'AD-'), (5, 'AD'), (6, 'AD+'), (7, 'D-'), (8, 'D'), (9, 'D+'), (10, 'ED-'), (11, 'ED'), (12, 'ED+'), (13, 'EDx')], default=0)),
                ('aid_climbing_grade', models.IntegerField(blank=True, choices=[(0, 'A0'), (1, 'A1'), (2, 'A2'), (3, 'A3'), (4, 'A4'), (5, 'A5')], null=True)),
                ('ice_climbing_grade', models.IntegerField(blank=True, choices=[(0, 'WI1'), (1, 'WI2'), (2, 'WI3'), (3, 'WI4'), (4, 'WI5'), (5, 'WI6'), (6, 'WI7')], null=True)),
                ('rock_climbing_grade', models.IntegerField(blank=True, choices=[(0, '3A'), (1, '4A'), (2, '4B'), (3, '4C'), (4, '5A'), (5, '5B'), (6, '5C'), (7, '6A'), (8, '6B'), (9, '6C'), (10, '7A'), (11, '7B'), (12, '7C'), (13, '8A'), (14, '8B'), (15, '8C'), (16, '9A'), (17, '9B'), (18, '9C')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gpx', models.FileField(blank=True, null=True, upload_to='gpx')),
                ('kml', models.FileField(blank=True, null=True, upload_to='kml')),
                ('mountain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cerros.mountain')),
                ('parent_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cerros.route')),
                ('references', models.ManyToManyField(blank=True, to='cerros.reference')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='Ascent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_format', models.IntegerField(choices=[(0, 'Year'), (1, 'Month and Year'), (2, 'Day, Month and Year')], default=2)),
                ('andinists', models.ManyToManyField(blank=True, to='cerros.andinist')),
                ('references', models.ManyToManyField(blank=True, to='cerros.reference')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerros.route')),
                ('support_andinists', models.ManyToManyField(blank=True, related_name='support_andinists', to='cerros.andinist')),
            ],
            options={
                'verbose_name': 'Ascenso',
                'verbose_name_plural': 'Ascensos',
            },
        ),
        migrations.AddField(
            model_name='andinist',
            name='references',
            field=models.ManyToManyField(blank=True, to='cerros.reference'),
        ),
        migrations.AddField(
            model_name='club',
            name='references',
            field=models.ManyToManyField(blank=True, to='cerros.reference'),
        ),
        migrations.AddField(
            model_name='mountain',
            name='references',
            field=models.ManyToManyField(blank=True, to='cerros.reference'),
        ),
        migrations.AddField(
            model_name='mountaingroup',
            name='references',
            field=models.ManyToManyField(blank=True, to='cerros.reference'),
        ),
    ]
