# Generated by Django 4.1.3 on 2022-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0005_reference_alter_andinist_options_alter_club_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mountain',
            options={'verbose_name': 'Montaña', 'verbose_name_plural': 'Montañas'},
        ),
        migrations.AddField(
            model_name='route',
            name='unregistered_non_sport_ascent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='unregistered_sport_ascent',
            field=models.BooleanField(default=False),
        ),
    ]
