# Generated by Django 4.1.3 on 2022-12-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0006_alter_mountain_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='andinist',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='ascended',
            field=models.BooleanField(default=True),
        ),
    ]
