# Generated by Django 4.1.3 on 2022-12-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0008_alter_nomenclaturasummit_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclaturasummit',
            name='cod_revision',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nomenclaturasummit',
            name='id_nomenclatura',
            field=models.CharField(max_length=255),
        ),
    ]
