# Generated by Django 4.1.3 on 2022-12-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0009_alter_nomenclaturasummit_cod_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclaturasummit',
            name='altitude_igm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomenclaturasummit',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nomenclaturasummit',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
