# Generated by Django 4.1.3 on 2022-12-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0010_alter_nomenclaturasummit_altitude_igm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclaturasummit',
            name='altitude_igm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
