# Generated by Django 4.1.3 on 2022-12-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0011_alter_nomenclaturasummit_altitude_igm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
