# Generated by Django 4.1.3 on 2022-12-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0012_alter_mountain_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
