# Generated by Django 4.1.3 on 2022-12-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0013_alter_mountain_latitude_alter_mountain_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainprefix',
            name='prefix',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
