# Generated by Django 4.1.3 on 2022-12-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0014_alter_mountainprefix_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andinist',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='andinist',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
