# Generated by Django 4.1.3 on 2022-12-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0015_alter_andinist_name_alter_andinist_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andinist',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
