# Generated by Django 4.1.3 on 2022-12-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0016_alter_andinist_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ascent',
            options={'ordering': ['date'], 'verbose_name': 'Ascenso', 'verbose_name_plural': 'Ascensos'},
        ),
        migrations.AlterModelOptions(
            name='mountain',
            options={'ordering': ['id'], 'verbose_name': 'Montaña', 'verbose_name_plural': 'Montañas'},
        ),
        migrations.AddField(
            model_name='ascent',
            name='first_ascent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ascent',
            name='new_route',
            field=models.BooleanField(default=False),
        ),
    ]
