# Generated by Django 4.1.3 on 2022-12-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0018_rename_first_ascent_ascent_is_first_ascent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='andinist',
            name='ascent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='andinist',
            name='first_ascent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='andinist',
            name='new_routes_count',
            field=models.IntegerField(default=0),
        ),
    ]
