# Generated by Django 4.1.3 on 2022-12-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0019_andinist_ascent_count_andinist_first_ascent_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['publication_name', 'publication_edition', 'publication_year', 'title', 'author', 'page', 'url'], 'verbose_name': 'Referencia', 'verbose_name_plural': 'Referencias'},
        ),
        migrations.AddField(
            model_name='mountain',
            name='first_absolute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_absolute', to='cerros.ascent'),
        ),
    ]
