# Generated by Django 4.1.3 on 2022-12-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerros', '0020_alter_reference_options_mountain_first_absolute'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='unregistered_non_sport_ascent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mountain',
            name='unregistered_sport_ascent',
            field=models.BooleanField(default=False),
        ),
    ]
