# Generated by Django 5.2.18 on 2026-10-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerros", "0028_alter_country_options_alter_mountaingroup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="tb_medium",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="image",
            name="width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
